# Generated by Django 6.0.1 on 2026-01-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='name',
            new_name='user',
        ),
    ]
