# Generated by Django 6.0.1 on 2026-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_rename_name_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.CharField(default='hii everyone', max_length=100),
        ),
    ]
