# Generated by Django 6.0.1 on 2026-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField()),
                ('certificate', models.BooleanField(default=True)),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='course_img')),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('levels', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermedaite'), ('advanced', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instrctor_name', models.CharField(max_length=100)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
    ]
