# Generated by Django 5.2 on 2026-01-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='instrctor_name',
            new_name='instructor_name',
        ),
    ]
