# Generated by Django 6.0.2 on 2026-05-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, help_text='Upload an MP4 / WebM lecture video.', null=True, upload_to='section_videos/')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Approximate duration in minutes.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first).')),
                ('is_preview', models.BooleanField(default=False, help_text='Free preview for non-enrolled users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.coursesyllabus')),
            ],
            options={
                'verbose_name': 'Syllabus Section',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
